### ISSUE TITLE
Localization files top element 

### ISSUE THREAD

**Issue by erictuvesson** [translation/rails#15]
_We had this problem a few weeks ago, I think it still applies._

When generating with languages like "da-DK", "de-DE" etc. Then the top element becomes "da", "de" etc. 

We just changed it since...
```
# file: localization.da-DK.yml
...
# You can edit and/or add new localization keys here, they won't be touched by Translation.io.
...
```

**Comment by MichaelHoste** [comment]
Hi @ChillyFlashER,

I don't understand the issue.

Are you talking about the top element in the YAML file? Which on, `translation.*.yml` or `localization.*.yml`?

The top element should be the same as the languages you defined in the `config/translation.rb` file.

Could you be more specific about your issue and paste some snipped of your configuration and problematic YAML files?

(Sorry for the delay, I'll try to be more reactive from now)

**Comment by ChillyFlashER** [comment]
Hi,

When we first setup new languages the top element in the YAML file the header didn't match the language code. 

This was a while ago and I haven't tried it again. It might just have been something to do with our first setup that went wrong or something similar.

So when we generated new files for languages like _da-DK_ it produced a file like this.
```
## Source: config/locales/localization.da-DK.yml
# THIS FILE CONTAINS LOCALIZATION KEYS : date and number formats, number precisions,
# number separators and all non-textual values depending on the language.
# These values must not reach the translator, so they are separated in this file.
#
# More info here: https://translation.io/blog/gettext-is-better-than-rails-i18n#localization
#
# You can edit and/or add new localization keys here, they won't be touched by Translation.io.
#
# If you want to add a new localization key prefix, use the option described here:
# https://github.com/aurels/translation-gem#custom-localization-key-prefixes
#
---
da:
  ...
```
And the gem was looking for _da-DK_ so it couldn't find the translations, we fixed it by manually changing all the keys of languages that has a dash in it.

**Comment by MichaelHoste** [comment]
Thanks @ChillyFlashER, 

I understood the issue, I'll try to reproduce this error but it seems weird, it should definitely work as expected.

I'll keep you in touch.

**Comment by MichaelHoste** [comment]
I can confirm that you are absolutely right. It only impacts `localization.xx.yml` files (not `translation.xx.yml` files).

It still works quite good since "de-DE" fallbacks to "de" and "da-DK" fallbacks to "da". But I need to fix this. Thanks a lot!

**Comment by MichaelHoste** [comment]
That should have been recently fixed. Thanks for the feedback!
