### ISSUE TITLE
Global upload

### ISSUE THREAD

**Issue by david-a-wheeler** [translation/rails#17]
I need to be able to do a global search and replace on all the locale translations. For example, turning all &lt;i&gt; into &lt;em&gt;. It would be great to support an upload _to_ translation.io, as well as download from.

**Comment by MichaelHoste** [comment]
Hi David,

You have 2 solutions for this: 

 * **The simple one:** use the search to find all the `<em>` and replace them manually in the translation interface of https://translation.io. It can take several minutes to make the changes but that's really not so bad. And then just execute `rake translation:sync`

<img width="604" alt="capture d ecran 2017-06-03 a 19 24 28" src="https://cloud.githubusercontent.com/assets/529357/26755672/a8ac96aa-4892-11e7-8c15-db6502d818cf.png">


 * **The less simple one**: Make all the changes in your codebase (in the YAML files themselves) and initialize (`rake translation:init`) a new project with another API key. Of course the history will be lost and you'll need to invite the collaborators again on the project, but sometimes, for big changes, it's worth it.

My guess is that for your situation, the first solution would be less obtrusive.

**Comment by david-a-wheeler** [comment]
The first is much easier in my case :').

**Comment by MichaelHoste** [comment]
I close this issue since it seems that the solution 1 worked.

We have plans in the following months to create a friendly API to do mass edits like this.

In the meantime, creating a new project and "rake translation:init" again is usually the best solution when a lot of changes is involved.
