### ISSUE TITLE
Isn't it possible to only use gettext?

### ISSUE THREAD

**Issue by waldyr** [translation/rails#26]
Since I'm using gettext I tried to remove every other yml translation file. Long story short I couldn't.

The closest I got was to add the prefixes of keys on the ignored keys but I ended up with an empty `translation.*.yml` and a populated `localization.*.yml`.

Env info:
```
ruby 2.6.0p0

rails 5.2.1

translation (1.17)
      gettext (~> 3.2, >= 3.2.5)
```

**Comment by MichaelHoste** [comment]
We weren't aware this use case could be interesting for some users, but it shouldn't be hard to implement.

Thanks for the feedback. We'll keep you in touch.

**Comment by MichaelHoste** [comment]
We added this feature in the last version of the gem ([v1.18](https://github.com/translation/rails/releases/tag/v1.18)).

`config.disable_yaml = true`

See here: https://github.com/translation/rails#disable-gettext-or-yaml
