### ISSUE TITLE
Deprecation warning for #has_rdoc (Rubygems)

### ISSUE THREAD

**Issue by erictuvesson** [translation/rails#29]
```
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /Users/eric/.rvm/gems/ruby-2.6.2/bundler/gems/translation-ff98468dc2da/translation.gemspec:13.
```

https://blog.rubygems.org/2011/03/28/1.7.0-released.html
https://blog.rubygems.org/2009/05/04/1.3.3-released.html

There doesn't seem to be any replacements, so I would suggest only removing the has_rdoc line.

**Comment by MichaelHoste** [comment]
The new released version ([v1.18](https://github.com/translation/rails/releases/tag/v1.18)) doesn't have this issue anymore. Thanks for the warning!
