### ISSUE TITLE
Do not add methods on Object

### ISSUE THREAD

**Issue by Systho** [translation/rails#30]
Currently ,  `TranslationIO.configure` ends with a lot of methods added to `Object` and delegated to `Proxy`

It is a code smell to add methods on Object, and may create lots of issues when using multiple translation system or migrating from one to another for example.

I would definitely prefer adding an `include TranslationIO::Proxy` in my classes than having these methods magically inherited.

Would you consider adding a mechanism similar to `disable_gettext` which would `disable_object_monkey_patching`  ? Maybe even make that the default in a future major version change ?

**Comment by MichaelHoste** [comment]
I tend to agree with you that it's not great to add methods to `Object`, and we're not proud of it. But it simplifies the localisation process and makes it work regardless of the context, and we like that.

So I would consider to add a `disable_object_monkey_patching` option and add a section in the docs to explain it, but I would not agree to make it the default behaviour.

Would it work for you?

Are you willing to create a pull request? I would be able to do it but not before a week or two.

**Comment by Systho** [comment]
i suggested making it a new default only in a new major release because I understand that it would break a lot of (probably all) application. For the moment, having an option to opt-out of monkey patching is already a good step forward.

I'm definitely not comfortable enough with the codebase for making a PR, I just happened to inherit an app using `_(...)` everywhere and I when I found out how this voodoo trick was performed I decided to share my opinion with you :)

I'm not in any urgency for a fix neither, I have other , larger, problems to fix in that inherited codebase :)

**Comment by MichaelHoste** [comment]
I added the option and documented it, a new gem version will be created tomorrow: 

* https://github.com/translation/rails/commit/fd3afd6b09f54f193c3680c7783f79d6391bdde7
* https://github.com/translation/rails#gettext-object-class-monkey-patching

Thank you for the suggestion! :-)
