### ISSUE TITLE
Unclear how to use custom locales in project

### ISSUE THREAD

**Issue by noon-ng** [translation/rails#33]
Hi all,

I'd like to use translation.io to manage copy for A/B tests in my Rails project, and the [custom languages feature](https://translation.io/blog/custom-languages) seems ideal for this.

I've tried using custom locales with the syntax suggested in the README but,

- the UI for creating a new project doesn't allow you to provide custom locales.
- it doesn't seem like you can use these custom locales in the initializer either, because GetText doesn't recognize them.

What steps should I be taking to use custom languages?

Thanks,
Nuno

PS: excellent project.

**Comment by noon-ng** [comment]
Some progress -- I think the issue was that the custom locale I was trying to use had underscores in it. Here's my breaking `config/initializers/translation.rb`

```
TranslationIO.configure do |config|
  config.api_key        = '...'
  config.source_locale  = 'en'
  config.target_locales = ['en-not_ready_on']
end
```

This raises a `GetText::Tools::MsgInit::ValidationError: Locale 'en-not_ready_on' is invalid. Please check if your specified locale is usable.` when running `rake translation:init`.

If I remove the underscores from the target locale name (to `en-notreadyon`), it works fine.

**Comment by MichaelHoste** [comment]
Hi @noon-ng,

As you mentioned, underscores are certainly the issue here. GetText doesn't deal correctly with them and we should have mentioned that in the README and blog post.

You can't create the custom languages in the UI, but if you add them into your config file and these custom target languages will be created for you.

Were you able to initialize your project correctly?

**Comment by noon-ng** [comment]
Hi @MichaelHoste, thanks for getting back to me. Yup -- it works as intended.

Now to figure out how multiple locales can be combined at the `I18n` level :)

**Comment by MichaelHoste** [comment]
I'm glad it worked!

I'm not sure what you mean by "combined locales" but maybe this page on i18n fallbacks will help: https://github.com/ruby-i18n/i18n/wiki/Fallbacks

I'll leave this ticket open until we update the docs 😄

**Comment by noon-ng** [comment]
Ace @MichaelHoste!
