### ISSUE TITLE
Crash on "rake translation:init"

### ISSUE THREAD

**Issue by elhowm** [translation/rails#34]
Hello

Here is my configuration:
```ruby
TranslationIO.configure do |config|
  config.api_key        = '...'
  config.source_locale  = 'en'
  config.target_locales = %w[en]

  # Uncomment this if you don't want to use gettext
  config.disable_gettext = true

  config.ignored_key_prefixes = %w[
    time.formats demo
  ]
end
```

So, it's crashed on:
```
> rake translation:init
...
rake aborted!
JSON::ParserError: Empty input () at line 1, column 1 [parse.c:951] in '<!DOCTYPE html>
```

The only one place where I have it is:
`mailer.html.erb`

By the config I thought that it shouldn't go to views at all. So, why it goes? And how to fix?

**Comment by MichaelHoste** [comment]
Hello @elhowm,

My first guess is that you used "en" as source and target languages, it doesn't make much sense and it seems to trigger a 500 error in the backend.

We will investigate that to return a more beautiful error in that situation but in the meantime try with a different target language and it should work.

**Comment by elhowm** [comment]
@MichaelHoste yep, you're right
I changed it to different one and it works for me now. The reason why I set "source = target" is because I wanted to see how it will look in the web interface and didn't want to make any translations on this step

**Comment by MichaelHoste** [comment]
Thank you for your feedback! We added a nice error message instead of a 500 error in the backend if this situation happens again.
