### ISSUE TITLE
getText method not translating text as supposed to after install and intialization

### ISSUE THREAD

**Issue by Lee1984** [translation/rails#36]
**What do you expect to happen?**

Installed translation gem with bundle install.

created a app and added the config/initializers/translation.rb

ran `bundle exec rake translation:init` and this actually produced a warning saying it could not find most of the translation YAML files (I believe it said) asking is this normal? etc and listed most of the locales I had listed in my initializer but I continued anyway.

Text should get translated to eg `es` or `ru` which is listed in my intializer. Also running `locale -a` seems to list all translation.io locales.

    locale -a
      C
    C.utf8
    POSIX
    af_ZA
    af_ZA.utf8
    am_ET
    am_ET.utf8
    ar_AE
    ar_AE.utf8
    ar_BH
    ...
**What actually happened?**

Text stays as default locale ie `en`

**Code to reproduce**

    I18n.with_locale(:ru) do
      puts I18n.locale 
      _('hello everyone, how are you today')
    end
    
    ru
    hello everybody, how are you today

**Version**

    translation (1.21)
    gettext (~> 3.2, >= 3.2.5)
    rails 6.0.0.1
    ruby 2.6.5

**Comment by MichaelHoste** [comment]
Hi @Lee1984 

Have you translated "hello everybody, how are you today" to Russian in the translation interface?

You should translate it (manually or using [this feature](https://translation.io/blog/automatic-translation-with-google-translate)), and then sync before the translation appears in your page.

I hope it helped

**Comment by Lee1984** [comment]
What about for blog posts etc text. Even with html embedded?

**Comment by MichaelHoste** [comment]
You can use GetText to translate blogs posts, even with HTML.

But I would advise against that. It's best to use only minimal HTML to not confuse your translators. Only for links or emphasis like `Hello <strong>world</strong>` but not something with `div`, `table`, `ul` or other document structure.

We assist translators but it's best to limit "code" into their work: https://translation.io/blog/highlighting-of-html-tags-and-interpolated-variables

For (long) blog posts, I think it's best to have them translated directly in your database. They usually should not really be part of your code anyway.

**Comment by Lee1984** [comment]
This is what I can't get, and, asked at the `globalize` github page for gems like globalize and Traco etc and even posted on SO about it [here](https://stackoverflow.com/questions/61829222/how-do-we-get-a-translation-in-the-view-on-render-for-a-rails-model-attr-eg-a-b) is why we need to store the translation in the db? 

Can't we just translate when we bring it, out of the db.

Imagine saving 20+ languages for each blog post on save, what a nightmare

**Comment by MichaelHoste** [comment]
> Imagine saving 20+ languages for each blog post on save, what a nightmare

If you want a human translation, I don't see any alternative.

But if you want a on-the-fly machine translation, like Google Translate, you can use this: https://www.w3schools.com/HOWTO/howto_google_translate.asp

Or use the Google Translate API to translate your blog post in 20+ languages. It's incredibly simple to use: https://github.com/googleapis/google-cloud-ruby/tree/master/google-cloud-translate

You don't need something more complicated than that.

**Comment by Lee1984** [comment]
Thats what I thought i18n was. It gets ran through a translator. I'll never understand why these gems like globalize make you store the translation if that is what they are doing for you on save. Provide a option to do it in the view file

Thanks for the links. That's exactly what it looks like I need. I hope it works in other browsers as well.

**Comment by MichaelHoste** [comment]
I'm glad I was able to help!

Have a great day
