### ISSUE TITLE
Deprecation warning on Rails 6

### ISSUE THREAD

**Issue by heelhook** [translation/rails#38]
It seems this gem is using some code that is deprecated in Rails 6. I get this when I ran an `rspec` with this gem loaded:

```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
```

See https://github.com/rails/rails/issues/36546 for more.

**Comment by MichaelHoste** [comment]
Hello @heelhook,

I successfully started and synced a Rails 6 project with the last gem version and I was not able to get this deprecation warning.

Also, I'm able to execute the test suite of this gem on Rails 6.0 without any warning.

Someone posted this comment yesterday, maybe it would fix your rspec issue? https://github.com/rails/rails/issues/36546#issuecomment-663930482

It seems however that this line could create some issues, we'll investigate, thank you!

https://github.com/translation/rails/blob/93a663c0afbf2fe24b82b3ee80f454afb719d486/lib/translation_io/railtie.rb#L11

**Comment by MichaelHoste** [comment]
The deprecation warnings should be fixed thanks to this: https://github.com/translation/rails/commit/fdae89e72c62c516b403c00a905e80a79347c2ea

I bumped the gem version to [1.22](https://github.com/translation/rails/commit/fdae89e72c62c516b403c00a905e80a79347c2ea), could you please execute `bundle update translation` and check that the warnings are correctly fixed?

Thank you for your feedback!

**Comment by heelhook** [comment]
Thanks! That took care of it 🚀

**Comment by MichaelHoste** [comment]
🍾

Thank you for your help!
