### ISSUE TITLE
When disabling gettext in the initialiser gettext directory and files are still created

### ISSUE THREAD

**Issue by gerard76** [translation/rails#43]
when moving an existing project over to translation.io I uncommented `config.disable_gettext = true` in the initialiser.

after running `rake transition:init` some .po and .pot file are still generated in a new config/locales/gettext directory.

I expected those files not to be generated when clearly stating I do not use gettext

**Comment by MichaelHoste** [comment]
if you use `config.disable_gettext = true`, Gettext directory will be created (useful for our process), then removed at this step: https://github.com/translation/rails/blob/master/lib/translation_io/client/base_operation.rb#L54

Are you sure `rake translation:init` finished without errors? I just tested it and it works, the directory is not there.

I'd be interested to know what went wrong to be able to fix it.

BTW, if you sync, it should also remove that directory. Could you please check to see if it's working?

**Comment by gerard76** [comment]
I can see sync creating and then removing the files. A double init will create and not remove them though. Maybe that is what happend. Problem solved though.

**Comment by MichaelHoste** [comment]
> A double init will create and not remove them though.

That's certainly what happened, thank you for this!

I close this issue since the files will disappear on the next successful task.
