### ISSUE TITLE
A way to exclude translation keys

### ISSUE THREAD

**Issue by cspeer** [translation/rails#45]
Hi,

I have a file in a project that I do not want by any means to be translated by a person or the auto translate service.
So, I'm wondering if there is a way to exclude translation keys or files so that the keys/files will not be sent to translation.io and/or auto-translated.

Thanks!

**Comment by MichaelHoste** [comment]
Hi @cspeer,

You can use the `config.ignored_key_prefixes` option to ignore key prefixes: https://github.com/translation/rails#ignored-yaml-keys

Usually a file starts with a root key, so you can use this to ignore complete YAML files.

**Comment by cspeer** [comment]
Thanks a lot @MichaelHoste I totally missed that when reading the docs.

**Comment by MichaelHoste** [comment]
I'm glad I was able to help!

Feel free to open new issues or contact us directly on contact@translation.io if you have more questions.
