### ISSUE TITLE
Technical Demo video from readme not working

### ISSUE THREAD

**Issue by cristielciu** [translation/rails#55]
Request URL: https://translation.io/videos/rails.mp4
Request Method: GET
Status Code: 401 Unauthorized

**Comment by didier-84** [comment]
Hi Christi,

Thanks for your issue. We had removed the video from our website a few months ago, but we forgot to update the README file in this repository.

I'm posting a copy of the video here below, for you to watch it:

https://github.com/translation/rails/assets/2227137/06442618-c220-412d-8a9d-15e0ad3dc75c

If you have any question, feel free to reach out to us on contact@translation.io

Also, you can try all features on Translation.io for free during your trial period (no credit card required.
